name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
                
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: escolalms/php:${{env.BRANCH}},escolalms/php:8
